apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: nm4x0a9vf-nodejs 
  janus-idp.io/tekton: nm4x0a9vf-nodejs
  backstage.io/kubernetes-id: nm4x0a9vf-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nm4x0a9vf-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml