apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: nm4x0a9vf-nodejs
  janus-idp.io/tekton: nm4x0a9vf-nodejs
  backstage.io/kubernetes-id: nm4x0a9vf-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nm4x0a9vf-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
