apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: nm4x0a9vf-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nm4x0a9vf-nodejs 
  name: nm4x0a9vf-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: nm4x0a9vf-nodejs 
